version: '3.8'

services:
  myartbot:
    build: .
    ports:
      - "127.0.0.1:8443:8443"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - USE_WEBHOOK=${USE_WEBHOOK:-false}
      - WEB_SERVER_HOST=127.0.0.1
      - WEB_SERVER_PORT=8443
    restart: unless-stopped
